next

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -15,8 +15,12 @@ jobs:
       
       - name: Ensure Staging Branch is successful
         run: |
-          curl -s "https://api.github.com/repos/codeyou-devops-with-aws-final-project-saleor-full/commits/staging/status" | jq '.statuses[0].state' | grep -q 'success'
-      
+          curl -s "https://api.github.com/repos/WTYLER9/codeyou-devops-with-aws-final-project-saleor-full/commits/staging/status" | jq '.statuses[0].state' | grep -q 'success'
+          if [[ "$STATUS" != "success" ]]; then
+            echo "Staging pipeline is not successful. Aborting deployment."
+            exit 1
+          fi
+          
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
