test4

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -10,18 +10,18 @@ jobs:
   stages:
     runs-on: ubuntu-latest
     steps:
-        - name: composing validation
-          run: |
-            docker compose -f docker-compose.yml up -d
-            docker compose ps
-            docker compose exec saleor-api curl -f http://localhost:8000/graphql || echo "something failed"
-            docker compose down
-
         - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
+
+        - name: composing validation
+          run: |
+            docker compose -f ./docker-compose.yml up -d
+            docker compose ps
+            docker compose exec saleor-api curl -f http://localhost:8000/graphql || echo "something failed"
+            docker compose down
 
         - name: build api docker
           run: 
