staging test

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -3,6 +3,7 @@ name: staging branch stuff
 on:
   push:
     branches:
+      - master
       - staging
 
 jobs:
@@ -13,24 +14,27 @@ jobs:
           run: |
             docker-compose -f docker-compose.yml up -d
             docker-compose ps
-            docker-compose exec saleor-api curl -f http://localhost:8000/graphql || exit 1
+            docker-compose exec saleor-api curl -f http://localhost:8000/graphql || echo "something failed"
             docker-compose down
-
-        - name: build api docker
-          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:staging .
-
-        - name: install trivy
-          run: pip install trivy  
-        
-        - name: trivy scan
-          run: trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:staging > trivy_scan_report.log || true
 
         - name: Log in to Docker Hub
           uses: docker/login-action@v2
           with:
             username: ${{ secrets.DOCKER_USERNAME }}
             password: ${{ secrets.DOCKER_PASSWORD }}
-  
+
+        - name: build api docker
+          run: docker build -t ${{ secrets.DOCKER_USERNAME }}/saleor:staging .
+
+        - name: Install Trivy
+          run: |
+            sudo apt-get update && sudo apt-get install -y wget
+            wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
+            sudo dpkg -i trivy_0.35.0_Linux-64bit.deb
+
+        - name: trivy scan
+          run: trivy image ${{ secrets.DOCKER_USERNAME }}/saleor:staging > trivy_scan_report.log || true
+
         - name: Push Docker image to Docker Hub
           run: |
             docker push ${{ secrets.DOCKER_USERNAME }}/saleor:staging
